name: Changeset Versioning

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository to Runner
        uses: actions/checkout@v3

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Changeset Versioning
        run: |
          npm ci
          npm i -g yarn
          yarn changeset version
      
      - name: GitHub Configuration setup
        run: |
          git config --local user.name ${{ github.actor }}
          git config --local user.email "nishkarshraj000@gmail.com"

      # Will fail on main because direct commits are not allowed without PR
      - name: Push to GitHub  
        run: |
          git add .
          git commit -s -m "[ci skip] Change Log upgraded & Changesets cleaned"
          git push -u origin ${{ github.ref }}
