name: Changeset Versioning

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository to Runner
        uses: actions/checkout@v3

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Changeset Versioning
        run: |
          npm ci
          npm i -g yarn
          yarn changeset version
      
      - name: GitHub Configuration setup
          git config --local user.name ${{ github.actor }}
          git config --local user.email "nishkarshraj000@gmail.com"

      - name: Stage Git changes    
          git add .
          git commit -m -s "[ci skip] Change Log upgraded & Changesets cleaned"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}


