name: Build Validation for Pull Requests

on: pull_request

jobs:
  build:

    # Need to test this on the matrix of all 3 major platforms and supported Node Versions
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository to Runner
        uses: actions/checkout@v3

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci
